/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPiano;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.sound.sampled.*;
import java.io.InputStream;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import java.io.*;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;

/**
 *
 * @author Bipul Islam
 */
public class MyPiano extends javax.swing.JFrame {

    /**
     * Creates new form MyPiano
     */
    public MyPiano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        CS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jchkMusic = new javax.swing.JCheckBox();
        jchkSteel = new javax.swing.JCheckBox();
        C = new javax.swing.JButton();
        DS = new javax.swing.JButton();
        D = new javax.swing.JButton();
        E = new javax.swing.JButton();
        FS = new javax.swing.JButton();
        F = new javax.swing.JButton();
        GS = new javax.swing.JButton();
        G = new javax.swing.JButton();
        AS = new javax.swing.JButton();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C1S = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        D1S = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setLayout(null);

        CS.setBackground(java.awt.Color.black);
        CS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CS.setForeground(new java.awt.Color(255, 255, 255));
        CS.setText("C#");
        CS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSActionPerformed(evt);
            }
        });
        jPanel1.add(CS);
        CS.setBounds(50, 120, 70, 170);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("My Piano");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 0, 230, 70);

        buttonGroup1.add(jchkMusic);
        jchkMusic.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jchkMusic.setForeground(java.awt.Color.white);
        jchkMusic.setText("Music Notes");
        jchkMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMusicActionPerformed(evt);
            }
        });
        jPanel1.add(jchkMusic);
        jchkMusic.setBounds(20, 70, 270, 40);

        buttonGroup1.add(jchkSteel);
        jchkSteel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jchkSteel.setForeground(java.awt.Color.white);
        jchkSteel.setText("Virtual Steel Drum");
        jchkSteel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSteelActionPerformed(evt);
            }
        });
        jPanel1.add(jchkSteel);
        jchkSteel.setBounds(480, 70, 360, 40);

        C.setBackground(java.awt.Color.white);
        C.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        C.setText("C");
        C.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        jPanel1.add(C);
        C.setBounds(20, 120, 60, 330);

        DS.setBackground(java.awt.Color.black);
        DS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DS.setForeground(java.awt.Color.white);
        DS.setText("D#");
        DS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSActionPerformed(evt);
            }
        });
        jPanel1.add(DS);
        DS.setBounds(130, 120, 71, 170);

        D.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        D.setText("D");
        D.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        jPanel1.add(D);
        D.setBounds(90, 120, 70, 330);

        E.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        E.setText("E");
        E.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        jPanel1.add(E);
        E.setBounds(170, 120, 70, 330);

        FS.setBackground(java.awt.Color.black);
        FS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        FS.setForeground(java.awt.Color.white);
        FS.setText("F#");
        FS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        FS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FSActionPerformed(evt);
            }
        });
        jPanel1.add(FS);
        FS.setBounds(290, 120, 70, 170);

        F.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        F.setText("F");
        F.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        jPanel1.add(F);
        F.setBounds(250, 120, 70, 330);

        GS.setBackground(java.awt.Color.black);
        GS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        GS.setForeground(java.awt.Color.white);
        GS.setText("G#");
        GS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSActionPerformed(evt);
            }
        });
        jPanel1.add(GS);
        GS.setBounds(370, 120, 71, 170);

        G.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        G.setText("G");
        G.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        jPanel1.add(G);
        G.setBounds(331, 120, 70, 330);

        AS.setBackground(java.awt.Color.black);
        AS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AS.setForeground(java.awt.Color.white);
        AS.setText("A#");
        AS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASActionPerformed(evt);
            }
        });
        jPanel1.add(AS);
        AS.setBounds(450, 120, 69, 170);

        A.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        A.setText("A");
        A.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        jPanel1.add(A);
        A.setBounds(410, 120, 70, 330);

        B.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B.setText("B");
        B.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        jPanel1.add(B);
        B.setBounds(490, 120, 70, 330);

        C1S.setBackground(java.awt.Color.black);
        C1S.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        C1S.setForeground(java.awt.Color.white);
        C1S.setText("C1#");
        C1S.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C1S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1SActionPerformed(evt);
            }
        });
        jPanel1.add(C1S);
        C1S.setBounds(620, 120, 83, 170);

        C1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        C1.setText("C1");
        C1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        jPanel1.add(C1);
        C1.setBounds(570, 120, 80, 330);

        D1S.setBackground(java.awt.Color.black);
        D1S.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        D1S.setForeground(java.awt.Color.white);
        D1S.setText("D1#");
        D1S.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D1S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1SActionPerformed(evt);
            }
        });
        jPanel1.add(D1S);
        D1S.setBounds(710, 120, 85, 170);

        D1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        D1.setText("D1");
        D1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        jPanel1.add(D1);
        D1.setBounds(660, 120, 90, 330);

        E1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        E1.setText("E1");
        E1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        jPanel1.add(E1);
        E1.setBounds(760, 120, 80, 330);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 870, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchkMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMusicActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jchkMusicActionPerformed

    private void jchkSteelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSteelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkSteelActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\c.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_CActionPerformed

    private void CSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSActionPerformed
        // TODO add your handling code here:
        
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\chash.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
    }//GEN-LAST:event_CSActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
        
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\d.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_DActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\e.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_EActionPerformed

    private void DSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\dhash.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_DSActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\f.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_FActionPerformed

    private void FSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FSActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\fhash.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_FSActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        // TODO add your handling code here:
        
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\g.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_GActionPerformed

    private void GSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\ghash.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_GSActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\a.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_AActionPerformed

    private void ASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\ahash.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ASActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\b.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_BActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\c1.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_C1ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\d1.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_D1ActionPerformed

    private void D1SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1SActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\d1hash.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_D1SActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\e1.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_E1ActionPerformed

    private void C1SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1SActionPerformed
        // TODO add your handling code here:
        
        InputStream iAudio;
        
        if(jchkMusic.isSelected())
        {
            try {
                iAudio = new FileInputStream (new File ("D:\\Downloads\\Music\\c1hash.wav"));
                AudioStream iMusic;
                iMusic = new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_C1SActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyPiano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton AS;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton C1;
    private javax.swing.JButton C1S;
    private javax.swing.JButton CS;
    private javax.swing.JButton D;
    private javax.swing.JButton D1;
    private javax.swing.JButton D1S;
    private javax.swing.JButton DS;
    private javax.swing.JButton E;
    private javax.swing.JButton E1;
    private javax.swing.JButton F;
    private javax.swing.JButton FS;
    private javax.swing.JButton G;
    private javax.swing.JButton GS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jchkMusic;
    private javax.swing.JCheckBox jchkSteel;
    // End of variables declaration//GEN-END:variables
}
